[2024-06-01T16:24:11.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T16:24:11.311+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.transform manual__2024-06-01T16:18:58.505397+00:00 [queued]>
[2024-06-01T16:24:11.326+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.transform manual__2024-06-01T16:18:58.505397+00:00 [queued]>
[2024-06-01T16:24:11.328+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-01T16:24:11.349+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-06-01 16:18:58.505397+00:00
[2024-06-01T16:24:11.396+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T16:24:11.392+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transform', 'manual__2024-06-01T16:18:58.505397+00:00', '--job-id', '174', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0m2ndqxw']
[2024-06-01T16:24:11.405+0000] {standard_task_runner.py:63} INFO - Started process 493 to run task
[2024-06-01T16:24:11.406+0000] {standard_task_runner.py:91} INFO - Job 174: Subtask transform
[2024-06-01T16:24:11.491+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-01T16:24:11.592+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.transform manual__2024-06-01T16:18:58.505397+00:00 [running]> on host c5ef054da447
[2024-06-01T16:24:11.760+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T16:18:58.505397+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T16:18:58.505397+00:00'
[2024-06-01T16:24:11.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T16:24:12.175+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T16:24:12.177+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 42, in transform
    pdf_link = soup.find("a", title="Sheet nhạc bài Chờ ngày lời hứa nở hoa")['href']  # Adjust selector
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-06-01T16:24:12.226+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=transform, run_id=manual__2024-06-01T16:18:58.505397+00:00, execution_date=20240601T161858, start_date=20240601T162411, end_date=20240601T162412
[2024-06-01T16:24:12.251+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 174 for task transform ('NoneType' object is not subscriptable; 493)
[2024-06-01T16:24:12.268+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-01T16:24:12.290+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-01T16:24:12.296+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
